Do not check latest release if updates disabled
noisetorch/NoiseTorch pull request #355
Opened 2022-08-06 17:53 UTC by denbeigh2000

Fixes #345

## Why

#345 stemmed from a Nixpkgs issue, where the author saw a timeout message while checking for updates: https://github.com/NixOS/nixpkgs/pull/179088#issuecomment-1167959829

This is actually due to this module-level function call, which calls out to github to check the latest current release.

https://github.com/noisetorch/NoiseTorch/blob/ebf595ba4bf4c8143b1c60b0a787e144dede5824/update.go#L81

## What

This moves the function call to an `init()` function, so we can avoid this check entirely if updates have been disabled (either through config file, or by build variable).

## Testing

 - I can build and run the program with `UPDATE_URL` both as normal and empty in the `Makefile`
 - I ran `gofmt`

2022-08-07 09:30 UTC, Technetium1 reviewed
I see nothing wrong with this, but needs more :eyes:

2022-08-08 04:13 UTC, TheDukeofErl commented
The change here seems reasonable to me and I don't think we'll have any issues with the built-in updater like this. I'll just have to run a quick test to make sure that things seem to be in order, I'll plan on doing that tomorrow.

2022-08-09 14:10 UTC, TheDukeofErl requested changes

2022-08-09 14:11 UTC, TheDukeofErl commented on update.go
>  var currentVersion, _ = semver.Make(strings.TrimLeft(version, "v"))
Whoops, this should have been posted yesterday, but I didn't click the request changes button. Sorry for the delay.

2022-08-09 20:42 UTC, denbeigh2000 commented on update.go
>  var currentVersion, _ = semver.Make(strings.TrimLeft(version, "v"))
oh, nice! that would've been real subtle. will update this after work.

2022-08-10 02:47 UTC, denbeigh2000 commented
Updated, tested by setting the missing updateURL/pubkey in my local makefile, and ensuring I saw "Checking for updates" in the program output.

Thanks for the thorough validation here!

2022-08-11 00:34 UTC, TheDukeofErl commented on update.go
>  var currentVersion, _ = semver.Make(strings.TrimLeft(version, "v"))
Looks good to me now, marking this as resolved.

2022-08-11 00:35 UTC, TheDukeofErl approved these changes
LGTM!

2022-08-11 02:03 UTC, merged